export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const GET_DATA = "GET_DATA";
export const LIST_OF_BLOOD_GROUP = "LIST_OF_BLOOD_GROUP";

//Customers
export const LIST_OF_CUSTOMERS = "LIST_OF_CUSTOMERS";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const GET_CUSTOMER_BY_ID = "GET_CUSTOMER_BY_ID";
export const SEARCH_CUSTOMER = "SEARCH_CUSTOMER";
export const GET_CUSTOMER_LIST_BY_EXPEDITOR_ID =
  "GET_CUSTOMER_LIST_BY_EXPEDITOR_ID";

//Expeditor
export const LIST_OF_EXPEDITORS = "LIST_OF_EXPEDITORS";
export const ADD_EXPEDITOR = "ADD_EXPEDITOR";
export const DELETE_EXPEDITOR = "DELETE_EXPEDITOR";
export const UPDATE_EXPEDITOR = "UPDATE_EXPEDITOR";
export const GET_EXPEDITOR_BY_ID = "GET_EXPEDITOR_BY_ID";
export const ADD_EXPEDITOR_EXCEL = "ADD_EXPEDITOR_EXCEL";
export const GET_EXPEDITOR_BY_USERNAME = "GET_EXPEDITOR_BY_USERNAME";

//Product
export const LIST_OF_PRODUCTS = "LIST_OF_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCT_LIST_BY_ID_IS_NOT_CHANGED =
  "GET_PRODUCT_LIST_BY_ID_IS_NOT_CHANGED";
export const GET_PRODUCT_LIST_BY_ID_IS_CHANGED =
  "GET_PRODUCT_LIST_BY_ID_IS_CHANGED";
// export const GET_PRODUCT_LIST_BY_PROPERTY_ID_IS_CHANGED =
//   "GET_PRODUCT_LIST_BY_PROPERTY_ID_IS_CHANGED";
// export const GET_PRODUCT_LIST_BY_PROPERTY_ID_IS_NOT_CHANGED =
//   "GET_PRODUCT_LIST_BY_PROPERTY_ID_IS_NOT_CHANGED";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_PRODUCT_EXCEL = "ADD_PRODUCT_EXCEL";
export const ADD_PRODUCT_IMAGES = "ADD_PRODUCT_IMAGES";
export const GET_PRODUCT_IMAGES_BY_PRODUCT_ID =
  "GET_PRODUCT_IMAGES_BY_PRODUCT_ID";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
// export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
// export const GET_ALL_NEW_PRODUCTS = "GET_ALL_NEW_PRODUCTS";

//Category
export const LIST_OF_CATEGORIES = "LIST_OF_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

//Property
export const LIST_OF_PROPERTIES = "LIST_OF_PROPERTIES";
export const ADD_PROPERTY = "ADD_PROPERTY";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
export const GET_PROPERTY_BY_ID = "GET_PROPERTY_BY_ID";
export const GET_PROPERTY_BY_CATEGORY_ID = "GET_PROPERTY_BY_CATEGORY_ID";

//storehouse
export const LIST_OF_STOREHOUSE = "LIST_OF_STOREHOUSE";
export const GET_STOREHOUSE_BY_ID = "GET_STOREHOUSE_BY_ID";
export const ADD_STOREHOUSE = "ADD_STOREHOUSE";
export const UPDATE_STOREHOUSE = "UPDATE_STOREHOUSE";
export const DELETE_STOREHOUSE = "DELETE_STOREHOUSE";
export const LIST_OF_QUANTITIES = "LIST_OF_QUANTITIES";
export const GET_STORE_HOUSE_BY_BARCODE = "GET_STORE_HOUSE_BY_BARCODE";
export const GET_STORE_HOUSE_BY_QUANTITY = "GET_STORE_HOUSE_BY_QUANTITY";
export const STOREHOUSE_NUMERATE = "STOREHOUSE_NUMERATE";
export const STOREHOUSE_COUNT_COMBO = "STOREHOUSE_COUNT_COMBO";
export const STOREHOUSE_NUMERATE_RESULT = "STOREHOUSE_NUMERATE_RESULT";

//pagination
export const PAGINATION = "PAGINATION";

//page loader
export const PAGE_LOADING = "PAGE_LOADING";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

//auth
export const LOGIN_AUTH = "LOGIN_AUTH";

//CART
export const ADD_SALE = "ADD_SALE";
export const END_SALE = "END_SALE";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const UPDATE_BASKET = "UPDATE_BASKET";
export const DELETE_CART = "DELETE_CART";
export const SHOW_CART_BASKET_ITEMS = "SHOW_CART_BASKET_ITEMS";

//black list
export const ADD_BLACK_LIST_CUSTOMER = "ADD_BLACK_LIST_CUSTOMER";
export const SHOW_BLACK_LIST = "SHOW_BLACK_LIST";

//invoice
export const LIST_OF_INVOICES = "LIST_OF_INVOICES";
export const LIST_OF_INVOICE_TYPES = "LIST_OF_INVOICE_TYPES";
export const GET_INVOICE_BY_ID = "GET_INVOICE_BY_ID";
export const GET_INVOICES_BY_INVOICE_NUMBER = "GET_INVOICES_BY_INVOICE_NUMBER";

//restore
export const ADD_RESTORE = "ADD_RESTORE";
export const END_RESTORE = "END_RESTORE";
export const SHOW_RESTORE_BASKET_ITEMS = "SHOW_RESTORE_BASKET_ITEMS";

//retail
export const ADD_RETAIL = "ADD_RETAIL";
export const SHOW_RETAIL_BASKET_ITEMS = "SHOW_RETAIL_BASKET_ITEMS";
export const END_RETAIL = "END_RETAIL";

//cashbox
export const CASHBOX_TYPE_LIST = "CASHBOX_TYPE_LIST";
export const CASHBOX_ADD = "CASHBOX_ADD";

//income 
export const ADD_INCOME_TYPE="ADD_INCOME_TYPE"
export const LIST_OF_INCOME_TYPES="LIST_OF_INCOME_TYPES"

//cost 
export const ADD_COST_TYPE="ADD_COST_TYPE"
export const LIST_OF_COST_TYPES="LIST_OF_COST_TYPES"
