export const SHOW_MODAL="SHOW_MODAL"
export const HIDE_MODAL="HIDE_MODAL"
export const GET_DATA="GET_DATA"
export const LIST_OF_BLOOD_GROUP="LIST_OF_BLOOD_GROUP"

//Customers
export const LIST_OF_CUSTOMERS="LIST_OF_CUSTOMERS"
export const ADD_CUSTOMER="ADD_CUSTOMER"
export const DELETE_CUSTOMER="DELETE_CUSTOMER"
export const UPDATE_CUSTOMER="UPDATE_CUSTOMER"
export const GET_CUSTOMER_BY_ID="GET_CUSTOMER_BY_ID"

//Expeditor
export const LIST_OF_EXPEDITORS="LIST_OF_EXPEDITORS"
export const ADD_EXPEDITOR="ADD_EXPEDITOR"
export const DELETE_EXPEDITOR="DELETE_EXPEDITOR"
export const UPDATE_EXPEDITOR="UPDATE_EXPEDITOR"
export const GET_EXPEDITOR_BY_ID="GET_EXPEDITOR_BY_ID"

//Product
export const LIST_OF_PRODUCTS="LIST_OF_PRODUCTS"
export const GET_PRODUCT_BY_ID="GET_PRODUCT_BY_ID"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const ADD_PRODUCT="ADD_PRODUCT"

//CAtegory
export const LIST_OF_CATEGORIES="LIST_OF_CATEGORIES"

//Property
export const LIST_OF_PROPERTIES="LIST_OF_PROPERTIES"
