export default {
  paginationData: { page: "", pageSize: "" },
  data: [],
  dataById: {},
  modalType: null,
  modalProps: {},
  customerListData: [],
  customerDataListByExpeditorId: [],
  customerDataById: {},
  customerUpdateData: {},
  customerAddData: {},
  expeditorListData: [],
  expeditorDataById: {},
  expeditorUpdateData: {},
  expeditorAddData: {},

  productListData: [],
  productListDataByPage: {},
  productListDataByCategoryId:[],
  productDataById: {},
  productDeleteData: {},
  productAddData: {},
  productUpdateData: {},
  productImagesDataByProductId: [],
  searchProductData: {},

  categoryListData: [],
  categoryDataById: {},
  categoryAddData: {},
  categoryDeleteData: {},
  categoryUpdateData: {},

  propertyListData: [],
  propertyDataById: {},
  propertyDeleteData: {},
  propertyUpdateData: {},
  propertyAddData: {},

  storeHouseListData: [],
  storeHouseDataById: {},
  listOfQuantities: [],

  basketData:[],

  loading: false,
};
