export default {
  paginationData: { page: "", pageSize: "" },
  data: [],
  dataById: {},
  modalType: null,
  modalProps: {},
  customerListData: [],
  fetchCustomerData:[],
  customerDataListByExpeditorId: [],
  customerDataById: {},
  customerUpdateData: {},
  customerAddData: {},
  expeditorListData: [],
  expeditorDataById: {},
  expeditorUpdateData: {},
  expeditorAddData: {},

  productListData: [],
  productListDataByPage: {},
  productListDataByCategoryId: [],
  productListDataByPropertyId:[],
  totalPages:Number(),
  totalItems:Number(),
  productDataById: {},
  productDeleteData: {},
  productAddData: {},
  productUpdateData: {},
  productImagesDataByProductId: [],
  searchProductData: {},

  categoryListData: [],
  categoryDataById: {},
  categoryAddData: {},
  categoryDeleteData: {},
  categoryUpdateData: {},

  propertyListData: [],
  propertyDataById: {},
  propertyDeleteData: {},
  propertyUpdateData: {},
  propertyAddData: {},

  storeHouseListData: [],
  storeHouseDataById: {},
  listOfQuantities: [],

  basketData: {},
  basketGrandTotal: "",
  addBasketItems: [],
  basketAllData:{},

  loading: false,

  showBlackListData:[],
};
